on:
  push:
    branches: [ "developer" ]
  
jobs:
  
  Push_code_in_Dev:
    runs-on: ubuntu-latest
    name: Push_code_in_Dev
    environment: copy_code_in_dev
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Create PR to branch
      uses: LnkAsia/github-action-cherry-pick-@master
      with:
        pr_branch: 'dev'
        pr_labels: 'Push_code_in_Dev'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRY_RUN: false
