on:
  push:
    branches: [ "dev" ]
  
jobs:
  Deploy_to_dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Sleep for 10 seconds
      uses: dhaval210/wait-action@master
      with:
        time: '10s'
      
  release_pull_request:
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Create PR to branch
      uses: gorillio/github-action-cherry-pick@master
      with:
        pr_branch: 'preprod'
        pr_labels: 'preprod'
        pr_tital: 'push_in_preprod'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRY_RUN: false
