name: Build and Deploy to GKE - developer

on:
  push:
    branches:    
      - developer

jobs:
  Copy_code_in_development:
    runs-on: ubuntu-latest
    environment: copy_code_in_dev
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "dev"
        pr_title: "Pulling ${{ github.ref }} into dev"
        
  Copy_code_in_preprod:
    runs-on: ubuntu-latest
    environment: copy_code_in_pp
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "preprod"
        pr_title: "Pulling ${{ github.ref }} into preprod"

  Copy_code_in_prod:
    runs-on: ubuntu-latest
    environment: copy_code_in_prod
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "prod"
        pr_title: "Pulling ${{ github.ref }} into prod"

  call-workflow:
    uses: dhaval210/Rungis/.github/workflows/blank.yml@dev
    secrets: inherit
