on:
  push:
    branches: [ "preprod" ]
  workflow_call:
  
jobs:
  Deploy_to_preprod:
    runs-on: ubuntu-latest
    environment: pp

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Sleep for 10 seconds
      uses: dhaval210/wait-action@master
      with:
        time: '10s'
  call-workflow:
    uses: dhaval210/Rungis/.github/workflows/blank.yml@prod
    secrets: inherit
