name: Build and Deploy to GKE - developer

on:
  push:
    branches:    
      - dev

jobs:
  Copy_code_in_development:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "preprod"


#  call-workflow:
#    uses: dhaval210/odoodev/.github/workflows/Build and Deploy on GKE.yml@dev
#    secrets: inherit
