on:
  push:
    branches: [ "maintenance-prod" ]
  
jobs:
      
  Create_Pull-request_for_Production:
    runs-on: ubuntu-latest
    name: Create_Pull-request_for_Production
    environment: Create_Pull-request_for_Production
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Create PR to branch
      uses: LnkAsia/github-action-cherry-pick-@master
      with:
        pr_branch: 'prod'
        pr_labels: 'Merge_Request_for_Production'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRY_RUN: false
