on:
  push:
    branches: [ "preproduction" ]
  
  
jobs:
  Deploy_to_PreProd:
    runs-on: ubuntu-latest
    environment: Deploy_to_PreProd

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Sleep for 10 seconds
      uses: LnkAsia/wait-action-@master
      with:
        time: '10s'
