on:
  push:
    branches: [ "maintenance-preprod" ]
  
jobs:
        
  Create_Pull-request_for_preprod:
    runs-on: ubuntu-latest
    name: Create_Pull-request_for_preprod
    environment: Create_Pull-request_for_preprod
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Create PR to branch
      uses: LnkAsia/github-action-cherry-pick-@master
      with:
        pr_branch: 'preprod'
        pr_labels: 'Merge_Request_for_preprod'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRY_RUN: false
      

